name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
            cd rlink-develop
            git pull
            npm run production
            cd ../
            cd public_html
            rm -R build
            rm -R css
            rm -R js
            rm -R fonts
            rm -R images
            cd ../
            cd rlink-develop
            mv public/* ../public_html
