name: remote ssh command
on:
  push:
     branches:
        - staging_final       
  pull_request:
     branches:
        - staging_final
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST2 }}
        username: ${{ secrets.USERNAME2 }}
        password: ${{ secrets.PASSWORD2 }}
        port: ${{ secrets.PORT }}
        script: |
            cd /var/www/html/staging.stalinks.com
            git pull origin staging_final
            npm run production
            cd ../
