name: Deployment Automation
on:
  push:
     branches:
        - master      
  pull_request:
     branches:
        - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
            cd /var/www/html/stalinks.com
            git pull origin master
            npm run dev
            chmod -R 775 storage
            cd storage
            chmod -R 775 logs
            cd ../
